server:
  port: 9527

spring:
  application:
    name: AIGOU-ZUUL

zuul:
  ignoredServices: '*' 
  routes:
    plat:
      serviceId: AIGOU-PLAT
      path: /plat/**
    product:
      serviceId: AIGOU-PRODUCT
      path: /product/**
  prefix: /services